services:
  vector-quant-service:
    build: ./backend
    container_name: vector-quant-service
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/markets" ]
      interval: 30s
      timeout: 10s
      retries: 3

  vector-quant:
    build: ./frontend
    container_name: vector-quant
    restart: always
    ports:
      - "19110:8501"
    depends_on:
      vector-quant-service:
        condition: service_started
    volumes:
      - ./frontend:/app # Hot-reload for development
